name: Publish Python Package

on:
  push:
    tags:
      - "*.*.*"  # Trigger on version tags like 1.0.0

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: windows-latest

    permissions:
      id-token: write  # Required for Trusted Publishing
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Upgrade pip and install build tool
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
